# -*- coding: utf-8 -*-
"""modèle_gpt4mini_guide_segmenté_5runs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VuzpLgUevNWsVDqM9yWRQlJhm4gu0fs
"""

from openai import OpenAI
import pandas as pd
from tqdm import tqdm

client = OpenAI(api_key="")

import collections
# =========================
# 2. PROMPTS POUR CHAQUE TEST
# =========================

CRAN_PROMPT = """
Tu es linguiste annotateur. Réponds UNIQUEMENT par "OUI" ou "NON".

TEST CRAN — mot exclusivement figé
Question : l’expression contient-elle un mot exclusivement figé ?

Un mot exclusivement figé :
- n’existe pas comme mot autonome,
- n’apparaît jamais en dehors de l’expression,
- n’a plus d’usage productif moderne.

Exemple OUI : « us » dans « us et coutumes »
Exemple NON : « bleu » dans « cordon bleu »

Réponds uniquement OUI ou NON.
Puis ajoute UNE phrase très courte expliquant la raison.
Format obligatoire :
OUI/NON
Explication : <phrase très courte>

Expression : {expression}
Contexte : {contexte}
"""

MORPH_PROMPT = """
Tu es linguiste annotateur. Réponds UNIQUEMENT par "OUI" ou "NON".

TEST MORPH — modification morphologique
Question : la flexion (pluriel, genre) rend-elle l’expression agrammaticale ou étrange ?

Exemple OUI : « garde du corps » → « gardes du corps »
Exemple NON : « livre scolaire » → « livres scolaires »

Réponds uniquement OUI ou NON.
Puis ajoute UNE phrase très courte expliquant la raison.
Format obligatoire :
OUI/NON
Explication : <phrase très courte>

Expression : {expression}
Contexte : {contexte}
"""

SYNT_PROMPT = """
Tu es linguiste annotateur. Réponds UNIQUEMENT par "OUI" ou "NON".

TEST SYNT — modification syntaxique
Question : un changement d’ordre ou de structure modifie-t-il fortement le sens ou le rend-il agrammaticale ou bizzare ?

Exemple OUI : « pomme de terre » ≠ « pomme terrestre »
Exemple NON : « comité régional » ≈ « comité de la région »

Réponds uniquement OUI ou NON.
Puis ajoute UNE phrase très courte expliquant la raison.
Format obligatoire :
OUI/NON
Explication : <phrase très courte>

Expression : {expression}
Contexte : {contexte}
"""

LEX_PROMPT = """
Tu es linguiste annotateur. Réponds UNIQUEMENT par "OUI" ou "NON".

TEST LEX — substitution lexicale
Question : remplacer un élément par un synonyme rend-il l’expression anormale, agrammaticale ou bizzare ?

Exemple OUI : « eau de vie » → « boisson de vie »
Exemple NON : « prix réduit » → « tarif réduit »

Réponds uniquement OUI ou NON.
Puis ajoute UNE phrase très courte expliquant la raison.
Format obligatoire :
OUI/NON
Explication : <phrase très courte>

Expression : {expression}
Contexte : {contexte}
"""

MODIF_PROMPT = """
Tu es linguiste annotateur. Réponds UNIQUEMENT par "OUI" ou "NON".

TEST MODIF — insertion d’un modifieur
Question : l’insertion d’un modifieur (adjectif/adverbe) interne rend-elle l’expression anormale, agrammaticale ou bizzare ?

Exemple OUI : « pomme verte de terre »
Exemple NON : « roman contemporain policier »

Réponds uniquement OUI ou NON.
Puis ajoute UNE phrase très courte expliquant la raison.
Format obligatoire :
OUI/NON
Explication : <phrase très courte>

Expression : {expression}
Contexte : {contexte}
"""

SEMREST_PROMPT = """
Tu es linguiste annotateur. Réponds UNIQUEMENT par "OUI" ou "NON".

TEST SEM-REST — restrictions sémantiques
Question : la tête nominale (le nom principal de l'expression) telle qu'elle est utilisée dans cette expression (dans son sens contextuel) a-t-elle un ensemble restreint de collocatifs naturels ?

Exemple OUI : « professeur de linguistique » → mais aussi « professeur de maths », « professeur de chimie », « professeur de littérature » (ensemble restreint aux domaines académiques)
Exemple NON : « événement majeur » → mais aussi « événement local », « événement imprévu », « événement politique », etc. (ensemble très ouvert)

⚠️ Attention : Tu dois analyser UNIQUEMENT la tête nominale, pas l’expression entière.
On vérifie avec quels collocatifs naturels se combine la tête nominale seule.

Exemples :
- dans « roman policier » → la tête nominale = « roman », pas « roman policier »
- dans « pomme de terre » → la tête nominale = « pomme », pas « pomme de terre »

Ne prends jamais l’expression complète comme base de comparaison.
Toujours la tête nominale seule.


Réponds uniquement OUI ou NON.
Puis ajoute UNE phrase très courte expliquant la raison.
Format obligatoire :
OUI/NON
Explication : <phrase très courte>

Expression : {expression}
Contexte : {contexte}
"""

ID_PROMPT = """
Tu es linguiste annotateur. Réponds UNIQUEMENT par "OUI" ou "NON".

TEST ID — type naturel
Question : l’expression désigne-t-elle une sous-catégorie naturelle et littérale du noyau nominal ?


⚠️ Attention : tu dois identifier la tête syntaxique de l’expression :
le nom qui constitue le noyau de la construction nominale. L’objectif du test est de déterminer si l’expression désigne une sous-catégorie
naturelle de ce noyau.

Pour répondre OUI, le noyau nominal doit garder son sens et l’expression doit désigner un type de ce nom. La réponse est plus souvent OUI que NON, donc dans les cas d'incertitude penche vers OUI.

Exemples ID = NON :
- « île flottante » (dessert) : ce n’est pas un type d'île, c'est un dessert
- « forêt noire » (gâteau) : ce n’est pas un type de forêt, c'est un gâteau

Exemple ID = OUI :
- « événement culturel » : c’est un type d’événement
- « chaise en bois » : c’est un type de chaise
- « véhicule électrique » : c’est un type de véhicule
- « bouteille en plastique » : c’est un type de bouteille
- « porte coulissante » : c’est un type de porte



Réponds uniquement OUI ou NON.
Puis ajoute UNE phrase très courte expliquant la raison.
Format obligatoire :
OUI/NON
Explication : <phrase très courte>

Expression : {expression}
Contexte : {contexte}
"""

OPAC_PROMPT = """
Tu es linguiste annotateur. Réponds UNIQUEMENT par "OUI" ou "NON".

🔵 TEST OPAC — opacité sémantique

Question : le sens global ne correspond-il pas à la somme des sens littéraux des composants ?

Si le noyau nominal n’est pas littéral → OPAC = OUI.

Exemples OUI :
- « île flottante » (pas une île flotte)
- « forêt noire » (pas une forêt qui est noire)
- « lune de miel » (pas une lune construite de miel)

Exemples NON :
- « analyse des données » (c'est une analyse impliquant des données)
- « décision administrative » (c'est une déc ision qui est de type administratif)

Expression : « {expression} »
Contexte : {contexte}

Réponds uniquement OUI ou NON.
Puis ajoute UNE phrase très courte expliquant la raison.
Format obligatoire :
OUI/NON
Explication : <phrase très courte>

Expression : {expression}
Contexte : {contexte}
"""


# =========================
# 3. ВСПОМОГАТЕЛЬНАЯ ФУНКЦИЯ ДЛЯ ОДНОГО ТЕСТА
# =========================

def ask_test(prompt_template, expression, examples):
    contexte = "" if examples is None or pd.isna(examples) else str(examples)
    prompt = prompt_template.format(expression=expression, contexte=contexte)

    resp = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=50,
    )

    full = (resp.choices[0].message.content or "").strip()

    # первая строка = ответ OUI/NON
    first_line = full.split("\n")[0].strip().upper()

    decision = "OUI" if first_line == "OUI" else "NON"

    # объяснение = всё, что идёт после первой строки
    explanation = ""
    if "\n" in full:
        explanation = full.split("\n", 1)[1].strip()

    return decision, explanation


# =========================
# 4. ДЕРЕВО РЕШЕНИЙ ДЛЯ ВСЕХ ТЕСТОВ
# =========================

def annotate_expression(expression, examples, debug=False):
    tests = {}

    # CRAN
    d, e = ask_test(CRAN_PROMPT, expression, examples)
    tests["CRAN"] = (d, e)
    if d == "OUI":
        return tests, "expression_idiomatique"

    # MORPH
    d, e = ask_test(MORPH_PROMPT, expression, examples)
    tests["MORPH"] = (d, e)
    if d == "OUI":
        d2, e2 = ask_test(ID_PROMPT, expression, examples)
        tests["ID"] = (d2, e2)
        if d2 == "NON":
            return tests, "expression_idiomatique"
        d3, e3 = ask_test(OPAC_PROMPT, expression, examples)
        tests["OPAC"] = (d3, e3)
        return tests, ("collocation_opaque" if d3 == "OUI" else "collocation_transparente")

    # SYNT
    d, e = ask_test(SYNT_PROMPT, expression, examples)
    tests["SYNT"] = (d, e)
    if d == "OUI":
        d2, e2 = ask_test(ID_PROMPT, expression, examples)
        tests["ID"] = (d2, e2)
        if d2 == "NON":
            return tests, "expression_idiomatique"
        d3, e3 = ask_test(OPAC_PROMPT, expression, examples)
        tests["OPAC"] = (d3, e3)
        return tests, ("collocation_opaque" if d3 == "OUI" else "collocation_transparente")

    # LEX
    d, e = ask_test(LEX_PROMPT, expression, examples)
    tests["LEX"] = (d, e)
    if d == "OUI":
        d2, e2 = ask_test(ID_PROMPT, expression, examples)
        tests["ID"] = (d2, e2)
        if d2 == "NON":
            return tests, "expression_idiomatique"
        d3, e3 = ask_test(OPAC_PROMPT, expression, examples)
        tests["OPAC"] = (d3, e3)
        return tests, ("collocation_opaque" if d3 == "OUI" else "collocation_transparente")

    # MODIF
    d, e = ask_test(MODIF_PROMPT, expression, examples)
    tests["MODIF"] = (d, e)
    if d == "OUI":
        d2, e2 = ask_test(ID_PROMPT, expression, examples)
        tests["ID"] = (d2, e2)
        if d2 == "NON":
            return tests, "expression_idiomatique"
        d3, e3 = ask_test(OPAC_PROMPT, expression, examples)
        tests["OPAC"] = (d3, e3)
        return tests, ("collocation_opaque" if d3 == "OUI" else "collocation_transparente")

    # SEM-REST
    d, e = ask_test(SEMREST_PROMPT, expression, examples)
    tests["SEM-REST"] = (d, e)
    if d == "NON":
        return tests, "expression_libre"

    # ID
    d, e = ask_test(ID_PROMPT, expression, examples)
    tests["ID"] = (d, e)
    if d == "NON":
        return tests, "expression_idiomatique"

    # OPAC
    d, e = ask_test(OPAC_PROMPT, expression, examples)
    tests["OPAC"] = (d, e)
    return tests, ("collocation_opaque" if d == "OUI" else "collocation_transparente")



def annotate_with_majority_vote(expression, examples, n=5, debug=False):
    runs = []  # Сохраним (category, tests)

    for i in range(n):
        if debug:
            print(f"\n--- RUN {i+1}/{n} ---")
        tests, category = annotate_expression(expression, examples, debug=False)
        runs.append({"category": category, "tests": tests})

    # Подсчёт голосов
    all_categories = [r["category"] for r in runs]
    counter = collections.Counter(all_categories)

    # --- Новое правило ---
    # 1. проверяем, есть ли категории с ≥ 2 голосами (кроме expression_libre)
    major_candidates = [
        cat for cat, count in counter.items()
        if count >= 2 and cat != "expression_libre"
    ]

    if major_candidates:
        # Если есть хотя бы одна категория ≥ 2 и ≠ libre → выигрывает она/они
        if len(major_candidates) == 1:
            chosen = major_candidates[0]
            # тесты последнего запуска для этой категории
            chosen_tests = None
            for r in reversed(runs):
                if r["category"] == chosen:
                    chosen_tests = r["tests"]
                    break

            return {
                "votes": all_categories,
                "final_category": chosen,
                "tie": None,
                "tests": chosen_tests,
            }

        else:
            # Ничья между несколькими категориями, набравшими ≥2 голоса
            return {
                "votes": all_categories,
                "final_category": "/".join(major_candidates),
                "tie": major_candidates,
                "tests": None,
            }

    # 2. Если нет категорий ≥2 кроме expression_libre → проверяем expression_libre
    if counter.get("expression_libre", 0) >= 2:
        chosen = "expression_libre"
        chosen_tests = None
        # найдём последний запуск, где выбрали expression_libre
        for r in reversed(runs):
            if r["category"] == chosen:
                chosen_tests = r["tests"]
                break

        return {
            "votes": all_categories,
            "final_category": chosen,
            "tie": None,
            "tests": chosen_tests,
        }

    # 3. Если ни одна категория не набрала ≥2 голосов → чистая ничья между 1×1×1…
    tied = list(counter.keys())

    return {
        "votes": all_categories,
        "final_category": "/".join(tied),
        "tie": tied,
        "tests": None
    }


# =========================
# 5. ОБВЁРТКА ДЛЯ ЗАПИСИ В DATAFRAME
# =========================

def generate_annotation_with_llm(expression, examples, debug=False):
    result = annotate_with_majority_vote(
        expression, examples, n=5, debug=debug
    )

    votes = result["votes"]
    final_category = result["final_category"]
    tie = result.get("tie")
    tests = result.get("tests")

    lines = []

    # ---- ВСЕ ГОЛОСА ----
    lines.append("Votes :")
    for v in votes:
        lines.append(f"- {v}")

    # ---- ЕСЛИ БЫЛА НИЧЬЯ ----
    if tie:
        lines.append(f"\nÉGALITÉ : {', '.join(tie)}")

    # ---- ФИНАЛЬНАЯ КАТЕГОРИЯ ----
    lines.append(f"\nCATÉGORIE FINALE : {final_category}")

    # ---- ОБЪЯСНЕНИЯ ТЕСТОВ (если у выбранной категории есть tests) ----
    if tests:
        lines.append("\nExplications des tests menant à la catégorie finale :")
        order = ["CRAN", "MORPH", "SYNT", "LEX", "MODIF", "SEM-REST", "ID", "OPAC"]
        for t in order:
            if t in tests:
                decision, expl = tests[t]
                lines.append(f"{t} : {decision}")
                if expl:
                    lines.append(f"  Explication : {expl}")

    text = "\n".join(lines)

    if debug:
        print("\n=== RÉSUMÉ (majority vote + explications) ===\n")
        print(text)

    return text




# =========================
# 6. ОБРАБОТКА EXCEL
# =========================

chunk_file_path = "nominal_part_4.xlsx"
df_chunk = pd.read_excel(chunk_file_path)

df_chunk["llm_raw_response"] = None

for index, row in tqdm(
    df_chunk.iterrows(),
    total=len(df_chunk),
    desc="Annotation des expressions nominales",
    unit="expr",
):
    expression = row.get("expression")
    examples = row.get("examples_joined")

    if pd.isna(expression) or str(expression).strip() == "":
        df_chunk.at[index, "llm_raw_response"] = "N/A (missing expression)"
        continue

    debug_flag = index < 1  # дебаг только для первой строки

    llm_answer = generate_annotation_with_llm(
        expression=expression,
        examples=examples,
        debug=debug_flag,
    )

    df_chunk.at[index, "llm_raw_response"] = llm_answer

output_filename = "annotated_nominal_part_4_gpt4omini_segmented_tests.xlsx"
df_chunk.to_excel(output_filename, index=False)
print(f"Annotated and saved {output_filename}")